=== jagheterfredrik/java-idp/src/schemas/shibboleth-resolver-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:mace:shibboleth:resolver:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resolver="urn:mace:shibboleth:resolver:1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="AttributeResolver">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="SimpleAttributeDefinition" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseAttributeDefinition">
								<xs:attribute name="sourceName" type="xs:string" use="optional"/>
								<xs:attribute name="smartScope" type="xs:string" use="optional"/>
								<xs:attribute name="valueHandler" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PersistentIDAttributeDefinition" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseAttributeDefinition">
								<xs:sequence>
									<xs:element name="Salt">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute name="keyStorePath" type="xs:string" use="optional"/>
													<xs:attribute name="keyStoreKeyAlias" type="xs:string" use="optional"/>
													<xs:attribute name="keyStorePassword" type="xs:string" use="optional"/>
													<xs:attribute name="keyStoreKeyPassword" type="xs:string" use="optional"/>
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="sourceName" type="xs:string" use="optional"/>
								<xs:attribute name="scope" type="xs:string" use="required"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="CustomAttributeDefinition" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseAttributeDefinition">
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
								<xs:attribute name="class" type="xs:string" use="required"/>
								<xs:anyAttribute namespace="##any" processContents="lax"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="CustomDataConnector" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseDataConnector">
								<xs:sequence>
									<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
								<xs:attribute name="class" type="xs:string" use="required"/>
								<xs:anyAttribute namespace="##any" processContents="lax"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="JNDIDirectoryDataConnector" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseDataConnector">
								<xs:sequence>
									<xs:element name="Search">
										<xs:complexType>
											<xs:sequence minOccurs="0">
												<xs:element name="Controls">
													<xs:complexType>
														<xs:attribute name="searchScope" type="xs:string" use="optional"/>
														<xs:attribute name="timeLimit" type="xs:int" use="optional"/>
														<xs:attribute name="returningObjects" type="xs:boolean" use="optional"/>
														<xs:attribute name="linkDereferencing" type="xs:boolean" use="optional"/>
														<xs:attribute name="countLimit" type="xs:long" use="optional"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="filter" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="Property" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="value" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="JDBCDataConnector" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="resolver:BaseDataConnector">
								<xs:sequence>
									<xs:element name="Query" type="xs:string"/>
									<xs:element name="AttributeExtractor" minOccurs="0">
										<xs:complexType>
											<xs:attribute name="class" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="StatementCreator" minOccurs="0">
										<xs:complexType>
											<xs:sequence minOccurs="0" maxOccurs="unbounded">
												<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
											</xs:sequence>
											<xs:attribute name="class" type="xs:string" use="required"/>
											<xs:anyAttribute namespace="##any" processContents="lax"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="value" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="dbURL" type="xs:string" use="required"/>
								<xs:attribute name="dbDriver" type="xs:string" use="optional"/>
								<xs:attribute name="validationQuery" type="xs:string" use="optional" default="select 1"/>
								<xs:attribute name="maxActive" type="xs:integer" use="optional"/>
								<xs:attribute name="maxIdle" type="xs:integer" use="optional"/>
								<xs:attribute name="maxWait" type="xs:integer" use="optional"/>
								<xs:attribute name="minResultSet" type="xs:integer" use="optional"/>
								<xs:attribute name="maxResultSet" type="xs:integer" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="BaseAttributeDefinition">
		<xs:complexContent>
			<xs:extension base="resolver:BaseResolutionPlugIn">
				<xs:attribute name="lifeTime" type="xs:long" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="BaseDataConnector">
		<xs:complexContent>
			<xs:extension base="resolver:BaseResolutionPlugIn">
				<xs:sequence>
					<xs:element name="FailoverDependency" minOccurs="0">
						<xs:complexType>
							<xs:attribute name="requires" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="BaseResolutionPlugIn">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="DataConnectorDependency">
				<xs:complexType>
					<xs:attribute name="requires" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="AttributeDependency">
				<xs:complexType>
					<xs:attribute name="requires" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="cacheTime" type="xs:string" use="optional"/>
		<xs:attribute name="propagateErrors" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>
</xs:schema>

=== jagheterfredrik/java-idp/src/conf/resolver.ldap.xml
<AttributeResolver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mace:shibboleth:resolver:1.0" xsi:schemaLocation="urn:mace:shibboleth:resolver:1.0 shibboleth-resolver-1.0.xsd">
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonPrincipalName" smartScope="shibdev.edu">
		<DataConnectorDependency requires="directory"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonEntitlement">
		<DataConnectorDependency requires="directory"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonAffiliation">
		<DataConnectorDependency requires="directory"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonScopedAffiliation" smartScope="shibdev.edu">
		<AttributeDependency requires="urn:mace:eduPerson:1.0:eduPersonAffiliation"/>
	</SimpleAttributeDefinition>

	<JNDIDirectoryDataConnector id="directory">
		<Search filter="cn=%PRINCIPAL%">
			<Controls searchScope="SUBTREE_SCOPE" returningObjects="false" />
		</Search>
		<Property name="java.naming.factory.initial" value="com.sun.jndi.ldap.LdapCtxFactory" />
		<Property name="java.naming.provider.url" value="ldap://ldap.example.edu/dc=example,dc=edu" />
		<Property name="java.naming.security.principal" value="cn=admin,dc=example,dc=edu" />
		<Property name="java.naming.security.credentials" value="examplepw" />
	</JNDIDirectoryDataConnector>

</AttributeResolver>

=== jagheterfredrik/java-idp/src/conf/resolver.xml
<AttributeResolver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mace:shibboleth:resolver:1.0" xsi:schemaLocation="urn:mace:shibboleth:resolver:1.0 shibboleth-resolver-1.0.xsd">
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonEntitlement">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonAffiliation">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonNickname">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonPrimaryOrgUnitDN">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonOrgUnitDN">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonOrgDN">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	
	<!-- To use these attributes, you should change the smartScope value to match your site's domain name. -->
	<!--
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonScopedAffiliation" smartScope="shibdev.edu">
		<AttributeDependency requires="urn:mace:dir:attribute-def:eduPersonAffiliation"/>
	</SimpleAttributeDefinition>

	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonPrincipalName" smartScope="shibdev.edu">
    	<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	-->
	
	
	<!-- Example persistent id attribute.  You should change the scope value to match your site's domain 
		 name.  Since this configuration is permanent, some thought is required before deploying in 
		 production. -->
	<!--
	<PersistentIDAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonTargetedID" scope="shibdev.edu" sourceName="guid">
		<DataConnectorDependency requires="echo"/>
		<Salt keyStorePath="/conf/persistent.jks" keyStoreKeyAlias="handleKey" keyStorePassword="shibhs" keyStoreKeyPassword="shibhs"/>
	</PersistentIDAttributeDefinition>
	-->
	
	
	<!--Examples of common ldap-based attributes -->
	<!--
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:cn">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:sn">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:telephoneNumber">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:title">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:initials">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:description">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:carLicense">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:departmentNumber">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:displayName">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:employeeNumber">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:employeeType">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:preferredLanguage">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:manager">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:roomNumber">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:seeAlso">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:facsimileTelephoneNumber">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:street">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:postOfficeBox">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:postalCode">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:st">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:givenName">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:l">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:businessCategory">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:ou">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:physicalDeliveryOfficeName">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	-->
	
	
	<CustomDataConnector id="echo" class="edu.internet2.middleware.shibboleth.aa.attrresolv.provider.SampleConnector"/>

</AttributeResolver>

=== jagheterfredrik/java-idp/testresources/basicIdpHome/resolver.xml
<AttributeResolver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="urn:mace:shibboleth:resolver:1.0" 
	xsi:schemaLocation="urn:mace:shibboleth:resolver:1.0 ../../src/schemas/shibboleth-resolver-1.0.xsd">
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonEntitlement">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:title">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonAffiliation">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
		
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonScopedAffiliation"
		smartScope="example.org">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:telephoneNumber">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:cn">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:givenName">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
		
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:surname">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
		
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:unacceptable">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
			
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:unreleasable">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
			
	<SimpleAttributeDefinition id="urn:mace:dir:attribute-def:eduPersonPrincipalName"
		smartScope="example.org">
		<DataConnectorDependency requires="jutest"/>
	</SimpleAttributeDefinition>
					
	<CustomDataConnector id="jutest" class="edu.internet2.middleware.shibboleth.runner.AttributeSourceForTests"/>

</AttributeResolver>

=== jagheterfredrik/java-idp/data/resolver1.xml
<AttributeResolver xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mace:shibboleth:resolver:1.0" xsi:schemaLocation="urn:mace:shibboleth:resolver:1.0 shibboleth-resolver-1.0.xsd">
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonPrincipalName" smartScope="columbia.edu">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonNickName">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonEntitlement">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<SimpleAttributeDefinition id="urn:mace:eduPerson:1.0:eduPersonAffiliation">
		<DataConnectorDependency requires="echo"/>
	</SimpleAttributeDefinition>
	
	<CustomDataConnector id="echo" cacheTime="1800000"
		class="edu.internet2.middleware.shibboleth.aa.attrresolv.provider.SampleConnector" />

</AttributeResolver>
